# Generated by Django 2.2.7 on 2019-11-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20191118_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='score',
        ),
    ]
