# Generated by Django 2.2.7 on 2019-11-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_cases_evaluer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_state', to='stories.State'),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='stories.State'),
        ),
    ]
