# Generated by Django 2.2.7 on 2019-11-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20191120_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='studies',
        ),
    ]
